/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface NumberCounter {
        /**
          * @default 0
         */
        "initialCount": number;
    }
    interface ProgressBar {
    }
}
export interface ProgressBarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLProgressBarElement;
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLNumberCounterElement extends Components.NumberCounter, HTMLStencilElement {
    }
    var HTMLNumberCounterElement: {
        prototype: HTMLNumberCounterElement;
        new (): HTMLNumberCounterElement;
    };
    interface HTMLProgressBarElementEventMap {
        "progressMax": void;
    }
    interface HTMLProgressBarElement extends Components.ProgressBar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLProgressBarElementEventMap>(type: K, listener: (this: HTMLProgressBarElement, ev: ProgressBarCustomEvent<HTMLProgressBarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLProgressBarElementEventMap>(type: K, listener: (this: HTMLProgressBarElement, ev: ProgressBarCustomEvent<HTMLProgressBarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLProgressBarElement: {
        prototype: HTMLProgressBarElement;
        new (): HTMLProgressBarElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "number-counter": HTMLNumberCounterElement;
        "progress-bar": HTMLProgressBarElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface NumberCounter {
        /**
          * @default 0
         */
        "initialCount"?: number;
    }
    interface ProgressBar {
        "onProgressMax"?: (event: ProgressBarCustomEvent<void>) => void;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "number-counter": NumberCounter;
        "progress-bar": ProgressBar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "number-counter": LocalJSX.NumberCounter & JSXBase.HTMLAttributes<HTMLNumberCounterElement>;
            "progress-bar": LocalJSX.ProgressBar & JSXBase.HTMLAttributes<HTMLProgressBarElement>;
        }
    }
}
